language: go
  go:
    - "1.10"
before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script: go get github.com/Aorjoa/geekybase-api && go test
