language: go

go:
  - 1.11

branches:
  only:
    - master

env:
  - DEP_VERSION="0.3.2"

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - github.com/Aorjoa/geekybase-api

install:
  - dep ensure

script:
  - go test ./...