sudo: required

services:
  - docker

language: go

go:
  - 1.11

branches:
  only:
    - master

env:
  - DEP_VERSION="0.3.2"
  - IMAGE_NAME=aorjoa/geekybase-api

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
